# Enumerate all fixed violations.
show-fixes = true

# Categories
select = [
    "E", # error - pycodestyle
    "W", # warning - pycodestyle
    "F", # pyflakes
    "Q", # flake8-quotes
    "B", # flake8-bugbear
    "C90", # mccabe 
    "I", # isort 
    "N", # pep8-naming
    "UP", # pyupgrade 
    "ANN", # flake8-annotations
    "COM", # flake8-commas
    "PYI", # flake8-pyi
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PL" # Pylint
]

# Rules to ignore
ignore = [ 
    "ANN101" # Never enforce `ANN101` 	(missing type self).
]